doximity/es-elasticity

lib/elasticity/document.rb, lib/elasticity/version.rb, spec/units/document_spec.rb
currently if you try and run a query that has fields: [] in it, a nil.merge method will be thrown.  This handles that case by building the hash more cautiously.
=> allow simple fields

elasticity.gemspec, lib/elasticity/document.rb, lib/elasticity/strategies.rb, lib/elasticity/strategies/alias_index.rb, lib/elasticity/strategies/single_index.rb, lib/elasticity/version.rb, spec/units/strategies/single_index_spec.rb
Enable mappings and settings responses to mimic the JSON that would be
sent to the create index API.
1. [FIXED] `document_type` was not specified when fetching mappings and
settings and should be specified until this gem supports multiple
document types per index.
2. [FIXED] Fetching mappings and settings fails as the root node
returned from the API might not be the `index_name` due to aliases.
3. Updated elasticsearch gem to v1.0.12. Refer to [changelog](https://github.com/elastic/elasticsearch-ruby/blob/master/CHANGELOG.md#1012).
=> Mappings & Settings API Response

CHANGELOG, lib/elasticity/search.rb, lib/elasticity/version.rb, spec/functional/segmented_spec.rb
=> Fix issue with hash keys as strings and pagination methods

spec/functional/persistence_spec.rb
Elasticsearch is a little prone to error in situations which commands execute rapidly in an automated fashion. I added a check to make sure the cluster is healthy before each of the specs.
=> Investigate and fix spec failures in travis

lib/elasticity/multi_search.rb, lib/elasticity/search.rb, spec/units/multi_search_spec.rb, spec/units/search_spec.rb
This provides a total method on the multi search response object and makes it possible to work off of the returned object rather than having to build an array of arrays directly.  Shouldn't break backwards compatibility as consumers can still build a nested array via the `[]` if they wish to.
=> paginated multi search

CHANGELOG, README.md, lib/elasticity/bulk.rb, lib/elasticity/index_mapper.rb, lib/elasticity/version.rb, spec/functional/persistence_spec.rb
Implement bulk_update which allows document's attributes be updated individually instead of having to update the entire document.
=> bulk_update allows document's attributes be updated individually

lib/elasticity/base_document.rb, lib/elasticity/index_mapper.rb, spec/functional/persistence_spec.rb
The use case is a search that sorts results by distance using the function geo_distance, and I would like to present the calculated distance. Elasticsearch makes the calculated distance available in the sort property.
Example of `geo_distance` query and the returned `sort`. 
http://www.elasticsearchtutorial.com/spatial-search-tutorial.html
=> Access the sort array of each result.

CHANGELOG, lib/elasticity/multi_search.rb, lib/elasticity/version.rb
This will provide the key that the multi search query failed on so you know which indexes need to be rebuilt or which query needs to be modified.
=> multi search failure info

README.md
The writer meant to say "documents" instead of "document"
=> Minor typo fix in the Readme

CHANGELOG, lib/elasticity/multi_search.rb, lib/elasticity/search.rb, lib/elasticity/version.rb, spec/units/multi_search_spec.rb, spec/units/search_spec.rb
you can now pass any of the options found in
https://github.com/elastic/elasticsearch-ruby/blob/bdf5e145e5acc21726dddcd34492debbbddde568/elasticsearch-api/lib/elasticsearch/api/actions/search.rb#L125-L162
to a search definition.
=> expand search options

CHANGELOG, lib/elasticity/search.rb, lib/elasticity/version.rb, spec/units/search_spec.rb
elasticsearch ruby requires a body passed as part of the scan api so now
we pass one that complies with what the client requests.
https://github.com/elastic/elasticsearch-ruby/blob/5.x/elasticsearch-api/lib/elasticsearch/api/actions/scroll.rb
=> update scan api to work with modern versions of elasticsearch ruby

CHANGELOG, lib/elasticity/strategies/alias_index.rb, lib/elasticity/version.rb
Because of a bug in elasticsearch ruby gem the scan id must be passed
directly in the body.
https://github.com/elastic/elasticsearch-ruby/issues/423
=> fix bug in remap to use scan api properly

CHANGELOG, lib/elasticity/strategies/alias_index.rb, lib/elasticity/version.rb, spec/functional/persistence_spec.rb
If a field is not explicitly defined in an index's mapping we should not
persist it via the documents we copy over as part of remap.  This allows
for a way to get around the limitation in lucene where you can't delete
fields from index mappings without recreating the index from scratch.
=> update remap method to remove undefined mapping properties

CHANGELOG, lib/elasticity/index_config.rb, lib/elasticity/strategies/alias_index.rb, lib/elasticity/version.rb
a wildcard is still used to identify which indices to delete, but enabling destructive_requires_name is still safer because ad hoc scripts can't perform wildcard deletes
=> deleting with a wildcard is a risky setting that can be disabled

CHANGELOG, README.md, lib/elasticity/base_document.rb, lib/elasticity/index_mapper.rb, lib/elasticity/search.rb, lib/elasticity/version.rb, spec/functional/persistence_spec.rb, spec/functional/search_spec.rb
Adds the ability to request a `explain: true` on multisearch and regular searches.
Closes #47 
```ruby
search_with_explanation = SearchDoc.search(query_body, { explain: true }).search_results
search_a = SearchDoc::A.search(query_body, { explain: true })
search_b = SearchDoc::B.search(query_body, { explain: true })
search_c = SearchDoc::C.search(query_body, { explain: true })
multi = Elasticity::MultiSearch.new do |m|
m.add( :a, search_a, documents: ::SearchDoc::A)
m.add( :b, search_b, documents: ::SearchDoc::B)
m.add( :c, search_c, documents: ::SearchDoc::C)
end
```
- adds the ability to add search arguments to an elasticsearch query in both single index and multisearch queries.  
- implements `explain: true` 
- exposes `_explanation` as a public attr_reader on search and sets its value …
=> Add Explain Option for es-elasticity

CHANGELOG, lib/elasticity/base_document.rb, lib/elasticity/index_mapper.rb, lib/elasticity/version.rb, spec/functional/search_spec.rb
This PR adds a new attribute that gives es-elasticity the ability to preserve the general structure of request fields that are highlighted by Elasticsearch.
When the client requests fields to be highlighted from elasticsearch, IndexMapper will grab those highlighted fields and merge them directly into a new object so that the client can directly access the highlighted fields on the object when the result is returned.
```
{
description: "foo",
highlight: [
{ foo: ["<em>foo</em>"] }
]
}
document.foo => "foo"
document.highlighted.foo => ["<em>foo</em>"]
```
The current approach is great when we have a 1 to 1 mapping between what the client cares about and what elasticsearch is matching.  But we need to expose the highlight in order to either
- Displaying a subset on the view that *may* not …
=> Add ability to expose "highlight" to client

CHANGELOG, lib/elasticity/strategies/alias_index.rb, lib/elasticity/version.rb, spec/functional/persistence_spec.rb
Pivotal Tracker Story: https://www.pivotaltracker.com/story/show/159957541
associated Doximity PR https://github.com/doximity/doximity/pull/26007
errors during a `remap`, specifically trying to delete the index whilst a snapshot was in progress,  were leaving the cluster in a bad state
```
[404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"production_user_documents","index_uuid":"_na_","index":"production_user_documents"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"production_user_documents","index_uuid":"_na_","index":"production_user_documents"},"status":404}
```
This was because the main alias as not getting pointed back to the …
=> 159957541 fully clean up after error during remap

CHANGELOG, lib/elasticity/index_mapper.rb, lib/elasticity/strategies/alias_index.rb, lib/elasticity/version.rb, spec/functional/persistence_spec.rb
Pivotal Tracker story: https://www.pivotaltracker.com/story/show/160027841
related story https://www.pivotaltracker.com/story/show/159957541  and PR https://github.com/doximity/es-elasticity/pull/64
If a snapshot is in progress when we try to delete the old index
during a remap, the whole remap will fail. And it is only due to
bad timing.
That is an expensive errors since some remap can take 10s of hours.
So lets give the option of retrying that delete so we don't have
to waste all the cycles used during the remap
=> retry deleting the index after certain exceptions during remap

.travis.yml, CHANGELOG, elasticity.gemspec, lib/elasticity.rb, lib/elasticity/search.rb, lib/elasticity/version.rb
PT story https://www.pivotaltracker.com/story/show/167606136
Use `Arel.sql`  to avoid potentially unsafe sql (and quiet some deprecation warnings when used within a Rails project)
=> avoid unsafe sql with Arel

CHANGELOG, lib/elasticity/search.rb, lib/elasticity/version.rb
PT story https://www.pivotaltracker.com/story/show/169371020
Overview
--------
Initial work for the v7.2 upgrade was done under https://github.com/doximity/es-elasticity/pull/69
But that version caused some errors in downstream users of the gem.  The source of those errors was traced to the delegation of `to_ary` in `LazySearch` class.  That delegation seemed to be serving no purpose that I could find so I have removed it.
see https://github.com/doximity/doximity/pull/30869
=> remove to_ary delegation WIP

CHANGELOG.md, Gemfile.lock, lib/elasticity/base_document.rb, lib/elasticity/bulk.rb, lib/elasticity/config.rb, lib/elasticity/document.rb, lib/elasticity/index_config.rb, lib/elasticity/index_mapper.rb, lib/elasticity/instrumented_client.rb, lib/elasticity/log_subscriber.rb, lib/elasticity/multi_search.rb, lib/elasticity/multi_search_response_parser.rb, lib/elasticity/railtie.rb, lib/elasticity/search.rb, lib/elasticity/segmented_document.rb, lib/elasticity/strategies.rb, lib/elasticity/strategies/alias_index.rb, lib/elasticity/strategies/single_index.rb, lib/elasticity/version.rb, spec/functional/persistence_spec.rb, spec/rspec_config.rb, spec/units/document_spec.rb, spec/units/index_config_spec.rb, spec/units/index_mapper_spec.rb, spec/units/multi_search_response_parser_spec.rb, spec/units/multi_search_spec.rb, spec/units/search_spec.rb, spec/units/strategies/alias_index_spec.rb, spec/units/strategies/single_index_spec.rb
Jira story link: [MOFONETNAV-372]
We ran into an issue with version 1.0.0 where some classes, like `LogSubscriber`, are mutating strings. We'll wait to update these `frozen_string_literal` until the next release so we can isolate the changes.
- Revert the additional `frozen_string_literal` updates in 1.0.0 due to some issues with some classes. We'll update these in a separate release to isolate the problem.
[MOFONETNAV-372]: https://doximity.atlassian.net/browse/MOFONETNAV-372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Revert frozen string literal changes in 1.0.0

README.md
Jira link: [APPSEC-663](https://doximity.atlassian.net/browse/APPSEC-663)
We are migrating s3 buckets away from our `dox-legacy` aws account ahead of closing that account.
This PR updates references to that bucket, replacing them with a new bucket `dox-public-assets`. All the content has been migrated to this new bucket under the `/doximity` subdirectory, so the URLs are identical except for a new hostname prefix.
This should require no QA. We can spot-check the updated URLs to make sure they load in a browser.
This upgrade was automatically generated with `sourcegraph`.
[_Created by Sourcegraph batch change `jgran/doximity-s3`._](https://sourcegraph.build.dox.pub/users/jgran/batch-changes/doximity-s3)
=> Update `doximity` s3 bucket urls
